### ISSUE TITLE
Windows can't handle printing certain characters

### ISSUE THREAD

**Issue by bentsai** [covode/bible-fetch#9]
```
$ python bible luke 5:1-11
Traceback (most recent call last):
  File "bible", line 45, in <module>
    print(get_passage(soup))
  File "C:\bin\python\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 148: character maps to <undefined>
```

This can be isolated to simply running `print('\u2019')` interactively. Here is some information: https://wiki.python.org/moin/PrintFails

**Comment by bentsai** [comment]
This is less of a bug with bible fetch, but more of Windows' deficiencies.

http://stackoverflow.com/questions/878972/windows-cmd-encoding-change-causes-python-crash/3259271

**Comment by bentsai** [comment]
This should be fixed at the machine level: https://pypi.python.org/pypi/win_unicode_console
